server:
  port: 8082

spring:
  application:
    name: notification

  data:
    mongodb:
      uri: mongodb+srv://admin:admin@jaimecluster.svjzwdr.mongodb.net/notification-backend?retryWrites=true&w=majority

  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      default-zone: http://localhost:9000/eureka
    fetch-registry: true
    register-with-eureka: true